### ISSUE TITLE
is possible to get weight and surface area of models?

### ISSUE THREAD

**Issue by xurwxj** [all3dp/meshprop#1]
is possible to get weight and surface area of models?
thanks.

**Comment by xurwxj** [comment]
```
craster -u http://xxx.stl -n 10 -x 3 -y 15
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn phantomjs ENOENT
  at exports._errnoException (util.js:746:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
  at child_process.js:1144:20
  at process._tickCallback (node.js:355:11)
  at Function.Module.runMain (module.js:503:11)
  at startup (node.js:129:16)
  at node.js:814:3
```

**Comment by dreampulse** [comment]
Yes sure: the output includes the surface Area in mm^2 and the weight in mm^3 

```
{
  "volume" : 97177.8,  // <- the weight of the model
  "area" : 15730.4,
  "bbox" : {
    "x" : 71.054,
    "y" : 49.728,
    "z" : 95.002
  }
}
```

**Comment by xurwxj** [comment]
volume===weight?
surface area should be smaller than area when only with one face.

**Comment by dreampulse** [comment]
Take a look on the vcg-libaray (http://vcg.isti.cnr.it/vcglib/index.html)
I am simply using their interface.
